"""Generate migration script without database connection."""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.environment import EnvironmentContext
from alembic.autogenerate import compare_metadata

from app.core.config import settings
from app.models.core import Base
from app.models import *  # noqa: F403,F401 - import all models

# Create alembic config
config = Config("alembic.ini")

# Set target metadata
target_metadata = Base.metadata

def run_autogenerate(rev, message):
    """Generate migration using autogenerate."""
    
    # Create a script directory
    script_dir = ScriptDirectory.from_config(config)
    
    # Create environment context
    with EnvironmentContext(config, script_dir) as context:
        # Configure for offline mode (no DB connection)
        context.configure(
            url=settings.DATABASE_URL,
            target_metadata=target_metadata,
            literal_binds=False,
            dialect_opts={"paramstyle": "named"},
            compare_type=True,
            compare_server_default=True,
        )
        
        # Generate the revision
        def process_revision_directives(context, revision, directives):
            # This will be called with the autogenerated directives
            pass
        
        # Generate the revision
        script = script_dir.generate_revision(
            rev, message, 
            refresh=True, 
            head=script_dir.get_current_head(),
            process_revision_directives=process_revision_directives
        )
        return script

if __name__ == "__main__":
    try:
        script = run_autogenerate("head", "Initial schema: core domain models")
        print(f"Generated migration: {script.path}")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()