import { Model, Types } from 'mongoose';
import { MongoRepository } from './base.repository';
import { CalibrationProfile, ICalibrationProfile, CalibrationStatus, CalibrationMethod } from '../schemas/calibration.schema';

export class CalibrationRepository extends MongoRepository<ICalibrationProfile> {
  constructor(model: Model<ICalibrationProfile>) { super(model); }

  async findByCameraInstallation(cameraInstallationId: string, pagination?: { page: number; limit: number }): Promise<ICalibrationProfile[]> { const query = this.model.find({ cameraInstallationId: new Types.ObjectId(cameraInstallationId) }).sort({ version: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findActiveByCamera(cameraInstallationId: string): Promise<ICalibrationProfile | null> { return this.model.findOne({ cameraInstallationId: new Types.ObjectId(cameraInstallationId), status: CalibrationStatus.ACTIVE }).sort({ version: -1 }).exec(); }
  async findLatestByCamera(cameraInstallationId: string): Promise<ICalibrationProfile | null> { return this.model.findOne({ cameraInstallationId: new Types.ObjectId(cameraInstallationId) }).sort({ version: -1 }).exec(); }
  async findByStatus(status: CalibrationStatus, pagination?: { page: number; limit: number }): Promise<ICalibrationProfile[]> { const query = this.model.find({ status }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByMethod(method: CalibrationMethod, pagination?: { page: number; limit: number }): Promise<ICalibrationProfile[]> { const query = this.model.find({ method }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findValidated(): Promise<ICalibrationProfile[]> { return this.model.find({ status: CalibrationStatus.ACTIVE, 'validationResults.passed': true }).sort({ 'validationResults.validatedAt': -1 }).exec(); }
  async findPendingValidation(): Promise<ICalibrationProfile[]> { return this.model.find({ status: CalibrationStatus.PENDING_VALIDATION }).sort({ createdAt: 1 }).exec(); }
  async findNeedingRecalibration(maxError: number = 1.0): Promise<ICalibrationProfile[]> { return this.model.find({ status: CalibrationStatus.ACTIVE, 'metrics.reprojectionError': { $gt: maxError } }).sort({ 'metrics.reprojectionError': -1 }).exec(); }
  async activateProfile(id: string, activatedBy: Types.ObjectId): Promise<ICalibrationProfile | null> { await this.model.updateMany({ cameraInstallationId: (await this.model.findById(id))?.cameraInstallationId, status: CalibrationStatus.ACTIVE }, { status: CalibrationStatus.ARCHIVED }); return this.model.findByIdAndUpdate(id, { status: CalibrationStatus.ACTIVE, activatedAt: new Date(), activatedBy }, { new: true }).exec(); }
  async archiveProfile(id: string, archivedBy: Types.ObjectId): Promise<ICalibrationProfile | null> { return this.model.findByIdAndUpdate(id, { status: CalibrationStatus.ARCHIVED, archivedAt: new Date(), archivedBy }, { new: true }).exec(); }
  async setValidationResult(id: string, passed: boolean, details: Record<string, unknown>, validatedBy: Types.ObjectId): Promise<ICalibrationProfile | null> { return this.model.findByIdAndUpdate(id, { 'validationResults.passed': passed, 'validationResults.details': details, 'validationResults.validatedAt': new Date(), 'validationResults.validatedBy': validatedBy }, { new: true }).exec(); }
  async updateMetrics(id: string, metrics: Partial<ICalibrationProfile['metrics']>): Promise<ICalibrationProfile | null> { return this.model.findByIdAndUpdate(id, { $set: { metrics } }, { new: true }).exec(); }
  async updateAIProfile(id: string, aiMetadata: Partial<ICalibrationProfile['aiMetadata']>): Promise<ICalibrationProfile | null> { return this.model.findByIdAndUpdate(id, { $set: { aiMetadata } }, { new: true }).exec(); }
  async getCalibrationStats(): Promise<any> { const [total, draft, pending, active, archived, failed, byMethod, metrics] = await Promise.all([ this.model.countDocuments(), this.model.countDocuments({ status: CalibrationStatus.DRAFT }), this.model.countDocuments({ status: CalibrationStatus.PENDING_VALIDATION }), this.model.countDocuments({ status: CalibrationStatus.ACTIVE }), this.model.countDocuments({ status: CalibrationStatus.ARCHIVED }), this.model.countDocuments({ status: CalibrationStatus.FAILED }), this.model.aggregate([{ $group: { _id: '$method', count: { $sum: 1 } } }]), this.model.aggregate([{ $match: { status: CalibrationStatus.ACTIVE } }, { $group: { _id: null, avgError: { $avg: '$metrics.reprojectionError' } } }]), ]); return { total, draft, pending, active, archived, failed, byMethod: byMethod.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}), avgReprojectionError: metrics[0]?.avgError || 0 }; }
}