import { Model, Types } from 'mongoose';
import { MongoRepository } from './base.repository';
import { Camera, ICamera, CameraStatus, CameraMountType, CameraManufacturer } from '../schemas/camera.schema';

export class CameraRepository extends MongoRepository<ICamera> {
  constructor(model: Model<ICamera>) { super(model); }

  async findByCameraId(cameraId: string): Promise<ICamera | null> { return this.model.findOne({ cameraId: cameraId.toUpperCase() }).exec(); }
  async findByCourt(courtId: string, pagination?: { page: number; limit: number }): Promise<ICamera[]> { const query = this.model.find({ courtId: new Types.ObjectId(courtId) }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findActiveByCourt(courtId: string): Promise<ICamera[]> { return this.model.find({ courtId: new Types.ObjectId(courtId), status: { $in: [CameraStatus.ACTIVE, CameraStatus.CONNECTED, CameraStatus.CALIBRATED] } }).sort({ createdAt: -1 }).exec(); }
  async findBySerialNumber(serialNumber: string): Promise<ICamera | null> { return this.model.findOne({ serialNumber }).exec(); }
  async findByStatus(status: CameraStatus, pagination?: { page: number; limit: number }): Promise<ICamera[]> { const query = this.model.find({ status }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByMountType(mountType: CameraMountType, pagination?: { page: number; limit: number }): Promise<ICamera[]> { const query = this.model.find({ mountType }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByManufacturer(manufacturer: CameraManufacturer, pagination?: { page: number; limit: number }): Promise<ICamera[]> { const query = this.model.find({ manufacturer }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByCalibrationProfile(calibrationProfileId: string): Promise<ICamera[]> { return this.model.find({ calibrationProfileId: new Types.ObjectId(calibrationProfileId) }).exec(); }
  async findUncalibrated(): Promise<ICamera[]> { return this.model.find({ calibrationProfileId: { $exists: false }, status: { $in: [CameraStatus.REGISTERED, CameraStatus.CONNECTED, CameraStatus.ACTIVE] } }).sort({ createdAt: -1 }).exec(); }
  async findWithErrors(): Promise<ICamera[]> { return this.model.find({ status: CameraStatus.ERROR }).sort({ updatedAt: -1 }).exec(); }
  async findNeedingMaintenance(): Promise<ICamera[]> { return this.model.find({ status: CameraStatus.MAINTENANCE }).sort({ updatedAt: -1 }).exec(); }
  async updateHeartbeat(id: string): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { lastHeartbeat: new Date(), status: CameraStatus.CONNECTED }, { new: true }).exec(); }
  async updateStatus(id: string, status: CameraStatus, errorMessage?: string): Promise<ICamera | null> { const update: any = { status }; if (errorMessage) update.errorMessage = errorMessage; if (status === CameraStatus.ACTIVE) update.activatedAt = new Date(); if (status === CameraStatus.DECOMMISSIONED) update.decommissionedAt = new Date(); return this.model.findByIdAndUpdate(id, update, { new: true }).exec(); }
  async assignCalibrationProfile(id: string, calibrationProfileId: Types.ObjectId): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { calibrationProfileId, status: CameraStatus.CALIBRATED, calibratedAt: new Date() }, { new: true }).exec(); }
  async assignCoverageZone(id: string, coverageZoneId: Types.ObjectId): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { $addToSet: { assignedCoverageZones: coverageZoneId } }, { new: true }).exec(); }
  async removeCoverageZone(id: string, coverageZoneId: Types.ObjectId): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { $pull: { assignedCoverageZones: coverageZoneId } }, { new: true }).exec(); }
  async updatePosition(id: string, position: ICamera['position']): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { position, status: CameraStatus.CALIBRATING }, { new: true }).exec(); }
  async updateStreamConfig(id: string, streamConfig: ICamera['streamConfig']): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { streamConfig }, { new: true }).exec(); }
  async updateHealthMetrics(id: string, metrics: Partial<ICamera['healthMetrics']>): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { $set: { healthMetrics: metrics } }, { new: true }).exec(); }
  async recordError(id: string, error: string): Promise<ICamera | null> { return this.model.findByIdAndUpdate(id, { $inc: { 'healthMetrics.errorCount': 1 }, errorMessage: error, status: CameraStatus.ERROR }, { new: true }).exec(); }
  async getCameraStats(courtId: string): Promise<any> { const [total, active, calibrating, calibrated, error, maintenance, byMountType] = await Promise.all([ this.model.countDocuments({ courtId: new Types.ObjectId(courtId) }), this.model.countDocuments({ courtId: new Types.ObjectId(courtId), status: { $in: [CameraStatus.ACTIVE, CameraStatus.CONNECTED] } }), this.model.countDocuments({ courtId: new Types.ObjectId(courtId), status: CameraStatus.CALIBRATING }), this.model.countDocuments({ courtId: new Types.ObjectId(courtId), status: CameraStatus.CALIBRATED }), this.model.countDocuments({ courtId: new Types.ObjectId(courtId), status: CameraStatus.ERROR }), this.model.countDocuments({ courtId: new Types.ObjectId(courtId), status: CameraStatus.MAINTENANCE }), this.model.aggregate([{ $match: { courtId: new Types.ObjectId(courtId) } }, { $group: { _id: '$mountType', count: { $sum: 1 } } }]), ]); return { total, active, calibrating, calibrated, error, maintenance, byMountType: byMountType.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}) }; }
}