import { Model, Types } from 'mongoose';
import { MongoRepository } from './base.repository';
import { Court, ICourt, CourtStatus, MaintenanceStatus } from '../schemas/court.schema';

export class CourtRepository extends MongoRepository<ICourt> {
  constructor(model: Model<ICourt>) { super(model); }

  async findByCourtCode(venueId: string, courtCode: string): Promise<ICourt | null> { return this.model.findOne({ venueId: new Types.ObjectId(venueId), courtCode: courtCode.toUpperCase() }).exec(); }
  async findByVenue(venueId: string, pagination?: { page: number; limit: number }): Promise<ICourt[]> { const query = this.model.find({ venueId: new Types.ObjectId(venueId) }).sort({ courtCode: 1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findActiveByVenue(venueId: string): Promise<ICourt[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), status: CourtStatus.ACTIVE, maintenanceStatus: { $ne: MaintenanceStatus.IN_PROGRESS } }).sort({ courtCode: 1 }).exec(); }
  async findByType(courtType: string, pagination?: { page: number; limit: number }): Promise<ICourt[]> { const query = this.model.find({ courtType }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findBySurfaceType(surfaceType: string, pagination?: { page: number; limit: number }): Promise<ICourt[]> { const query = this.model.find({ surfaceType }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByStatus(status: CourtStatus, pagination?: { page: number; limit: number }): Promise<ICourt[]> { const query = this.model.find({ status }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByCameraProfile(cameraProfileId: string): Promise<ICourt[]> { return this.model.find({ cameraProfileId: new Types.ObjectId(cameraProfileId) }).exec(); }
  async findByCalibrationProfile(calibrationProfileId: string): Promise<ICourt[]> { return this.model.find({ calibrationProfileId: new Types.ObjectId(calibrationProfileId) }).exec(); }
  async findAvailableCourts(venueId: string, startDate: Date, endDate: Date): Promise<ICourt[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), status: CourtStatus.ACTIVE, maintenanceStatus: MaintenanceStatus.NONE, 'availability.isBookable': true, 'availability.blockoutDates': { $not: { $elemMatch: { $gte: startDate, $lte: endDate } } } }).sort({ courtCode: 1 }).exec(); }
  async findUnderMaintenance(): Promise<ICourt[]> { return this.model.find({ $or: [{ status: CourtStatus.MAINTENANCE }, { maintenanceStatus: { $in: [MaintenanceStatus.SCHEDULED, MaintenanceStatus.IN_PROGRESS] } }] }).sort({ maintenanceScheduledAt: 1 }).exec(); }
  async findOverdueMaintenance(): Promise<ICourt[]> { const now = new Date(); return this.model.find({ maintenanceStatus: { $in: [MaintenanceStatus.SCHEDULED, MaintenanceStatus.IN_PROGRESS] }, maintenanceScheduledAt: { $lt: now } }).sort({ maintenanceScheduledAt: 1 }).exec(); }
  async activateCourt(id: string, activatedBy: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { status: CourtStatus.ACTIVE, activatedAt: new Date(), activatedBy }, { new: true, runValidators: true }).exec(); }
  async setMaintenanceMode(id: string, status: MaintenanceStatus, scheduledAt?: Date, reason?: string): Promise<ICourt | null> { const update: any = { maintenanceStatus: status }; if (status === MaintenanceStatus.SCHEDULED) { update.status = CourtStatus.MAINTENANCE; update.maintenanceScheduledAt = scheduledAt; } else if (status === MaintenanceStatus.IN_PROGRESS) { update.status = CourtStatus.MAINTENANCE; } else if (status === MaintenanceStatus.COMPLETED) { update.maintenanceCompletedAt = new Date(); if (reason) update.metadata = { maintenanceReason: reason }; } else if (status === MaintenanceStatus.NONE) { update.maintenanceCompletedAt = new Date(); } return this.model.findByIdAndUpdate(id, update, { new: true, runValidators: true }).exec(); }
  async archiveCourt(id: string, archivedBy: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { status: CourtStatus.ARCHIVED, archivedAt: new Date(), archivedBy }, { new: true, runValidators: true }).exec(); }
  async restoreCourt(id: string): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { status: CourtStatus.DRAFT, archivedAt: null, archivedBy: null }, { new: true, runValidators: true }).exec(); }
  async assignCamera(id: string, cameraId: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { $addToSet: { assignedCameraIds: cameraId } }, { new: true, runValidators: true }).exec(); }
  async unassignCamera(id: string, cameraId: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { $pull: { assignedCameraIds: cameraId } }, { new: true, runValidators: true }).exec(); }
  async setCameraProfile(id: string, cameraProfileId: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { cameraProfileId }, { new: true, runValidators: true }).exec(); }
  async setCalibrationProfile(id: string, calibrationProfileId: Types.ObjectId): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { calibrationProfileId }, { new: true, runValidators: true }).exec(); }
  async updateAIConfiguration(id: string, config: Partial<ICourt['aiConfiguration']>): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { $set: { 'aiConfiguration': { ...config } } }, { new: true, runValidators: true }).exec(); }
  async addBlockoutDate(id: string, date: Date): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { $addToSet: { 'availability.blockoutDates': date } }, { new: true, runValidators: true }).exec(); }
  async removeBlockoutDate(id: string, date: Date): Promise<ICourt | null> { return this.model.findByIdAndUpdate(id, { $pull: { 'availability.blockoutDates': date } }, { new: true, runValidators: true }).exec(); }
  async getCourtStats(venueId: string): Promise<any> { const [total, active, maintenance, suspended, archived, byType, bySurface] = await Promise.all([ this.model.countDocuments({ venueId: new Types.ObjectId(venueId) }), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), status: CourtStatus.ACTIVE }), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), $or: [{ status: CourtStatus.MAINTENANCE }, { maintenanceStatus: { $in: [MaintenanceStatus.SCHEDULED, MaintenanceStatus.IN_PROGRESS] } }] }), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), status: CourtStatus.SUSPENDED }), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), status: CourtStatus.ARCHIVED }), this.model.aggregate([{ $match: { venueId: new Types.ObjectId(venueId) } }, { $group: { _id: '$courtType', count: { $sum: 1 } } }]), this.model.aggregate([{ $match: { venueId: new Types.ObjectId(venueId) } }, { $group: { _id: '$surfaceType', count: { $sum: 1 } } }]), ]); return { total, active, maintenance, suspended, archived, byType: byType.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}), bySurface: bySurface.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}) }; }
}