import { Model, Types } from 'mongoose';
import { MongoRepository } from './base.repository';
import { Facility, IFacility, FacilityType, FacilityStatus } from '../schemas/facility.schema';

export class FacilityRepository extends MongoRepository<IFacility> {
  constructor(model: Model<IFacility>) { super(model); }

  async findByFacilityCode(venueId: string, facilityCode: string): Promise<IFacility | null> { return this.model.findOne({ venueId: new Types.ObjectId(venueId), facilityCode: facilityCode.toUpperCase() }).exec(); }
  async findByVenue(venueId: string, pagination?: { page: number; limit: number }): Promise<IFacility[]> { const query = this.model.find({ venueId: new Types.ObjectId(venueId) }).sort({ facilityType: 1, name: 1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByType(facilityType: FacilityType, pagination?: { page: number; limit: number }): Promise<IFacility[]> { const query = this.model.find({ facilityType }).sort({ venueId: 1, name: 1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByStatus(status: FacilityStatus, pagination?: { page: number; limit: number }): Promise<IFacility[]> { const query = this.model.find({ status }).sort({ venueId: 1, facilityType: 1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByCourt(courtId: string): Promise<IFacility[]> { return this.model.find({ 'location.nearestCourt': new Types.ObjectId(courtId) }).exec(); }
  async findAvailable(venueId: string, startTime: Date, endTime: Date): Promise<IFacility[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), status: FacilityStatus.AVAILABLE, 'accessControl.accessHours': { $elemMatch: { start: { $lte: startTime.toTimeString().slice(0,5) }, end: { $gte: endTime.toTimeString().slice(0,5) } } } }).exec(); }
  async findByFloor(venueId: string, floor: string): Promise<IFacility[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), 'location.floor': floor }).sort({ name: 1 }).exec(); }
  async findWheelchairAccessible(venueId: string): Promise<IFacility[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), 'features.isWheelchairAccessible': true }).exec(); }
  async findWithEquipment(venueId: string): Promise<IFacility[]> { return this.model.find({ venueId: new Types.ObjectId(venueId), assignedEquipment: { $ne: [] } }).populate('assignedEquipment').exec(); }
  async updateStatus(id: string, status: FacilityStatus): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { status }, { new: true }).exec(); }
  async assignEquipment(id: string, equipmentId: Types.ObjectId): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { $addToSet: { assignedEquipment: equipmentId } }, { new: true }).exec(); }
  async removeEquipment(id: string, equipmentId: Types.ObjectId): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { $pull: { assignedEquipment: equipmentId } }, { new: true }).exec(); }
  async updateUtilization(id: string, hoursUsed: number): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { $inc: { 'utilizationMetrics.totalBookings': 1, 'utilizationMetrics.totalHoursUsed': hoursUsed }, $set: { 'utilizationMetrics.lastUpdated': new Date() } }, { new: true }).exec(); }
  async updateMaintenanceSchedule(id: string, lastMaintenance: Date, nextMaintenance: Date): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { 'maintenanceSchedule.lastMaintenance': lastMaintenance, 'maintenanceSchedule.nextMaintenance': nextMaintenance }, { new: true }).exec(); }
  async updateCleaningSchedule(id: string, lastCleaning: Date, nextCleaning: Date): Promise<IFacility | null> { return this.model.findByIdAndUpdate(id, { 'cleaningSchedule.lastCleaning': lastCleaning, 'cleaningSchedule.nextCleaning': nextCleaning }, { new: true }).exec(); }
  async getFacilityStats(venueId: string): Promise<any> { const [total, byType, byStatus, available, underMaintenance, capacity] = await Promise.all([ this.model.countDocuments({ venueId: new Types.ObjectId(venueId) }), this.model.aggregate([{ $match: { venueId: new Types.ObjectId(venueId) } }, { $group: { _id: '$facilityType', count: { $sum: 1 } } }]), this.model.aggregate([{ $match: { venueId: new Types.ObjectId(venueId) } }, { $group: { _id: '$status', count: { $sum: 1 } } }]), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), status: FacilityStatus.AVAILABLE }), this.model.countDocuments({ venueId: new Types.ObjectId(venueId), status: FacilityStatus.MAINTENANCE }), this.model.aggregate([{ $match: { venueId: new Types.ObjectId(venueId) } }, { $group: { _id: null, seated: { $sum: '$capacity.seated' }, standing: { $sum: '$capacity.standing' }, maxOccupancy: { $sum: '$capacity.maxOccupancy' } } }]), ]); return { total, byType: byType.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}), byStatus: byStatus.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}), available, underMaintenance, totalCapacity: capacity[0] || { seated: 0, standing: 0, maxOccupancy: 0 } }; }
}