import { Model, Types } from 'mongoose';
import { MongoRepository } from './base.repository';
import { Venue, IVenue, IVenueContact, VenueStatus } from '../schemas/venue.schema';

export class VenueRepository extends MongoRepository<IVenue> {
  constructor(model: Model<IVenue>) { super(model); }

  async findByVenueCode(venueCode: string): Promise<IVenue | null> { return this.model.findOne({ venueCode: venueCode.toUpperCase() }).exec(); }
  async findByOrganization(organizationId: string, pagination?: { page: number; limit: number }): Promise<IVenue[]> { const query = this.model.find({ organizationId: new Types.ObjectId(organizationId) }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findByOrganizationAndName(organizationId: string, venueName: string): Promise<IVenue | null> { return this.model.findOne({ organizationId: new Types.ObjectId(organizationId), venueName: { $regex: new RegExp(`^${venueName}$`, 'i') } }).exec(); }
  async findActiveByOrganization(organizationId: string): Promise<IVenue[]> { return this.model.find({ organizationId: new Types.ObjectId(organizationId), status: VenueStatus.ACTIVE }).sort({ venueName: 1 }).exec(); }
  async findByStatus(status: VenueStatus, pagination?: { page: number; limit: number }): Promise<IVenue[]> { const query = this.model.find({ status }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findNearby(longitude: number, latitude: number, maxDistanceKm: number = 50, pagination?: { page: number; limit: number }): Promise<IVenue[]> { const query = this.model.find({ coordinates: { $near: { $geometry: { type: 'Point', coordinates: [longitude, latitude] }, $maxDistance: maxDistanceKm * 1000 } }, status: VenueStatus.ACTIVE }).sort({ createdAt: -1 }); if (pagination) query.skip((pagination.page - 1) * pagination.limit).limit(pagination.limit); return query.exec(); }
  async findRequiringCertification(): Promise<IVenue[]> { return this.model.find({ certificationRequired: true, $or: [{ certificationId: { $exists: false } }, { certificationId: null }] }).exec(); }
  async activateVenue(id: string, activatedBy: Types.ObjectId): Promise<IVenue | null> { return this.model.findByIdAndUpdate(id, { status: VenueStatus.ACTIVE, activatedAt: new Date(), activatedBy }, { new: true, runValidators: true }).exec(); }
  async suspendVenue(id: string, suspendedBy: Types.ObjectId, reason: string): Promise<IVenue | null> { return this.model.findByIdAndUpdate(id, { status: VenueStatus.SUSPENDED, suspendedAt: new Date(), suspendedBy, suspendedReason: reason }, { new: true, runValidators: true }).exec(); }
  async archiveVenue(id: string, archivedBy: Types.ObjectId): Promise<IVenue | null> { return this.model.findByIdAndUpdate(id, { status: VenueStatus.ARCHIVED, archivedAt: new Date(), archivedBy }, { new: true, runValidators: true }).exec(); }
  async restoreVenue(id: string): Promise<IVenue | null> { return this.model.findByIdAndUpdate(id, { status: VenueStatus.DRAFT, archivedAt: null, archivedBy: null }, { new: true, runValidators: true }).exec(); }
  async addContact(id: string, contact: IVenueContact): Promise<IVenue | null> { return this.model.findByIdAndUpdate(id, { $push: { contacts: contact } }, { new: true, runValidators: true }).exec(); }
  async removeContact(id: string, contactIndex: number): Promise<IVenue | null> { const venue = await this.model.findById(id); if (!venue) return null; venue.contacts.splice(contactIndex, 1); return venue.save(); }
  async updateContact(id: string, contactIndex: number, contact: Partial<IVenueContact>): Promise<IVenue | null> { const venue = await this.model.findById(id); if (!venue) return null; venue.contacts[contactIndex] = { ...venue.contacts[contactIndex].toObject(), ...contact }; return venue.save(); }
  async setPrimaryContact(id: string, contactIndex: number): Promise<IVenue | null> { const venue = await this.model.findById(id); if (!venue) return null; venue.contacts.forEach((c, i) => { c.isPrimary = i === contactIndex; }); return venue.save(); }
  async getVenueStats(organizationId: string): Promise<any> { const [total, active, suspended, archived, draft, byType] = await Promise.all([ this.model.countDocuments({ organizationId: new Types.ObjectId(organizationId) }), this.model.countDocuments({ organizationId: new Types.ObjectId(organizationId), status: VenueStatus.ACTIVE }), this.model.countDocuments({ organizationId: new Types.ObjectId(organizationId), status: VenueStatus.SUSPENDED }), this.model.countDocuments({ organizationId: new Types.ObjectId(organizationId), status: VenueStatus.ARCHIVED }), this.model.countDocuments({ organizationId: new Types.ObjectId(organizationId), status: VenueStatus.DRAFT }), this.model.aggregate([{ $match: { organizationId: new Types.ObjectId(organizationId) } }, { $group: { _id: '$venueType', count: { $sum: 1 } } }]), ]); return { total, active, suspended, archived, draft, byType: byType.reduce((acc, item) => ({ ...acc, [item._id]: item.count }), {}) }; }
}