import { Schema, model, models, Types, HydratedDocument, Document } from 'mongoose';

export enum DocumentCategory { VENUE_PLAN = 'venue_plan', COURT_LAYOUT = 'court_layout', CERTIFICATE = 'certificate', INSPECTION_REPORT = 'inspection_report', MAINTENANCE_LOG = 'maintenance_log', CALIBRATION_REPORT = 'calibration_report', SAFETY_AUDIT = 'safety_audit', FIRE_CERTIFICATE = 'fire_certificate', STRUCTURAL_CERTIFICATE = 'structural_certificate', ELECTRICAL_CERTIFICATE = 'electrical_certificate', ACCESSIBILITY_CERTIFICATE = 'accessibility_certificate', ENVIRONMENTAL_CERTIFICATE = 'environmental_certificate', INSURANCE = 'insurance', PERMIT = 'permit', LICENSE = 'license', CONTRACT = 'contract', WARRANTY = 'warranty', MANUAL = 'manual', SPECIFICATION = 'specification', DRAWING = 'drawing', PHOTO = 'photo', VIDEO = 'video', OTHER = 'other' }
export enum DocumentStatus { DRAFT = 'draft', PENDING_REVIEW = 'pending_review', APPROVED = 'approved', REJECTED = 'rejected', EXPIRED = 'expired', ARCHIVED = 'archived', SUPERSEDED = 'superseded' }
export enum DocumentAccessLevel { PUBLIC = 'public', ORGANIZATION = 'organization', VENUE = 'venue', COURT = 'court', RESTRICTED = 'restricted', CONFIDENTIAL = 'confidential' }

export interface IDocumentVersion { version: number; fileUrl: string; fileSize: number; mimeType: string; checksum: string; uploadedAt: Date; uploadedBy: Types.ObjectId; changesSummary: string; isCurrent: boolean; }
export interface IDocument extends Document { documentCode: string; title: string; description?: string; category: DocumentCategory; status: DocumentStatus; accessLevel: DocumentAccessLevel; venueId?: Types.ObjectId; courtId?: Types.ObjectId; facilityId?: Types.ObjectId; equipmentId?: Types.ObjectId; certificationId?: Types.ObjectId; maintenanceId?: Types.ObjectId; currentVersion: IDocumentVersion; versions: IDocumentVersion[]; tags: string[]; metadata: { author?: string; department?: string; project?: string; confidentiality?: string; retentionPeriodDays?: number; expiryDate?: Date; reviewDate?: Date; approvedAt?: Date; approvedBy?: Types.ObjectId; rejectedAt?: Date; rejectedBy?: Types.ObjectId; rejectionReason?: string; }; relatedDocuments: Types.ObjectId[]; supersededBy?: Types.ObjectId; supersedes?: Types.ObjectId; downloadCount: number; lastAccessedAt?: Date; lastAccessedBy?: Types.ObjectId; retentionPolicy: { retainUntil: Date; autoArchive: boolean; autoDelete: boolean; legalHold: boolean; }; metadata: Record<string, unknown>; createdBy: Types.ObjectId; updatedBy?: Types.ObjectId; createdAt: Date; updatedAt: Date; }

const DocumentVersionSchema = new Schema({ version: { type: Number, required: true, min: 1 }, fileUrl: { type: String, required: true }, fileSize: { type: Number, required: true, min: 0 }, mimeType: { type: String, required: true }, checksum: { type: String, required: true }, uploadedAt: { type: Date, default: Date.now }, uploadedBy: { type: Schema.Types.ObjectId, required: true, ref: 'User' }, changesSummary: { type: String, required: true, trim: true }, isCurrent: { type: Boolean, default: true } }, { _id: false });
const DocumentMetadataSchema = new Schema({ author: { type: String, trim: true }, department: { type: String, trim: true }, project: { type: String, trim: true }, confidentiality: { type: String, trim: true }, retentionPeriodDays: { type: Number, min: 1 }, expiryDate: { type: Date }, reviewDate: { type: Date }, approvedAt: { type: Date }, approvedBy: { type: Schema.Types.ObjectId, ref: 'User' }, rejectedAt: { type: Date }, rejectedBy: { type: Schema.Types.ObjectId, ref: 'User' }, rejectionReason: { type: String, trim: true } }, { _id: false });

const DocumentSchema = new Schema(
  { documentCode: { type: String, required: true, unique: true, trim: true, uppercase: true, maxlength: 50 }, title: { type: String, required: true, trim: true, maxlength: 300 }, description: { type: String, trim: true, maxlength: 5000 }, category: { type: String, enum: Object.values(DocumentCategory), required: true }, status: { type: String, enum: Object.values(DocumentStatus), default: DocumentStatus.DRAFT }, accessLevel: { type: String, enum: Object.values(DocumentAccessLevel), default: DocumentAccessLevel.ORGANIZATION }, venueId: { type: Schema.Types.ObjectId, ref: 'Venue' }, courtId: { type: Schema.Types.ObjectId, ref: 'Court' }, facilityId: { type: Schema.Types.ObjectId, ref: 'Facility' }, equipmentId: { type: Schema.Types.ObjectId, ref: 'Equipment' }, certificationId: { type: Schema.Types.ObjectId, ref: 'Certification' }, maintenanceId: { type: Schema.Types.ObjectId, ref: 'MaintenanceRecord' }, currentVersion: { type: DocumentVersionSchema, required: true }, versions: { type: [DocumentVersionSchema], default: [] }, tags: [{ type: String, trim: true, lowercase: true }], metadata: { type: DocumentMetadataSchema, default: {} }, relatedDocuments: [{ type: Schema.Types.ObjectId, ref: 'Document' }], supersededBy: { type: Schema.Types.ObjectId, ref: 'Document' }, supersedes: { type: Schema.Types.ObjectId, ref: 'Document' }, downloadCount: { type: Number, default: 0, min: 0 }, lastAccessedAt: { type: Date }, lastAccessedBy: { type: Schema.Types.ObjectId, ref: 'User' }, retentionPolicy: { retainUntil: { type: Date, required: true }, autoArchive: { type: Boolean, default: true }, autoDelete: { type: Boolean, default: false }, legalHold: { type: Boolean, default: false } }, createdBy: { type: Schema.Types.ObjectId, required: true, ref: 'User' }, updatedBy: { type: Schema.Types.ObjectId, ref: 'User' } },
  { timestamps: true, collection: 'documents' }
);

DocumentSchema.index({ venueId: 1, category: 1 }); DocumentSchema.index({ courtId: 1, category: 1 }); DocumentSchema.index({ facilityId: 1, category: 1 }); DocumentSchema.index({ equipmentId: 1, category: 1 }); DocumentSchema.index({ certificationId: 1 }); DocumentSchema.index({ maintenanceId: 1 }); DocumentSchema.index({ status: 1 }); DocumentSchema.index({ accessLevel: 1 }); DocumentSchema.index({ tags: 1 }); DocumentSchema.index({ 'metadata.expiryDate': 1 }); DocumentSchema.index({ 'metadata.reviewDate': 1 }); DocumentSchema.index({ createdBy: 1 }); DocumentSchema.index({ documentCode: 1 }, { unique: true });

DocumentSchema.virtual('isExpired').get(function () { if (!this.metadata.expiryDate) return false; return this.metadata.expiryDate < new Date(); });
DocumentSchema.virtual('isExpiringSoon').get(function () { if (!this.metadata.expiryDate) return false; const thirtyDaysFromNow = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); return this.metadata.expiryDate <= thirtyDaysFromNow && this.metadata.expiryDate >= new Date(); });
DocumentSchema.virtual('isPendingReview').get(function () { if (!this.metadata.reviewDate) return false; return this.metadata.reviewDate <= new Date(); });
DocumentSchema.virtual('latestVersion').get(function () { return this.versions.find((v) => v.isCurrent) || this.currentVersion; });
DocumentSchema.virtual('versionCount').get(function () { return this.versions.length + 1; });

DocumentSchema.methods.addVersion = function (fileUrl: string, fileSize: number, mimeType: string, checksum: string, uploadedBy: Types.ObjectId, changesSummary: string) { const newVersion = this.currentVersion.version + 1; this.versions.push({ ...this.currentVersion, isCurrent: false }); this.currentVersion = { version: newVersion, fileUrl, fileSize, mimeType, checksum, uploadedAt: new Date(), uploadedBy, changesSummary, isCurrent: true }; return this.save(); };
DocumentSchema.methods.approve = function (approvedBy: Types.ObjectId) { this.status = DocumentStatus.APPROVED; this.metadata.approvedAt = new Date(); this.metadata.approvedBy = approvedBy; return this.save(); };
DocumentSchema.methods.reject = function (rejectedBy: Types.ObjectId, reason: string) { this.status = DocumentStatus.REJECTED; this.metadata.rejectedAt = new Date(); this.metadata.rejectedBy = rejectedBy; this.metadata.rejectionReason = reason; return this.save(); };
DocumentSchema.methods.archive = function () { this.status = DocumentStatus.ARCHIVED; return this.save(); };
DocumentSchema.methods.supersede = function (newDocumentId: Types.ObjectId) { this.status = DocumentStatus.SUPERSEDED; this.supersededBy = newDocumentId; return this.save(); };

export const $1Schema = $2Schema;;;;
export const Document = models.Document || model<IDocument>('Document', DocumentSchema);








