import { Schema, model, models, Types, HydratedDocument, Document } from 'mongoose';

export enum FacilityType { LOBBY = 'lobby', LOCKER_ROOM = 'locker_room', RESTROOM = 'restroom', MEDICAL_ROOM = 'medical_room', REFEREE_ROOM = 'referee_room', COACH_ROOM = 'coach_room', PLAYER_LOUNGE = 'player_lounge', VIP_LOUNGE = 'vip_lounge', MEDIA_ROOM = 'media_room', CONTROL_ROOM = 'control_room', SERVER_ROOM = 'server_room', STORAGE = 'storage', EQUIPMENT_ROOM = 'equipment_room', WEIGHT_ROOM = 'weight_room', REHABILITATION = 'rehabilitation', CAFETERIA = 'cafeteria', CONCESSION = 'concession', MERCHANDISE = 'merchandise', FIRST_AID = 'first_aid', SECURITY_OFFICE = 'security_office', ADMINISTRATION = 'administration', MEETING_ROOM = 'meeting_room', BROADCAST_BOOTH = 'broadcast_booth', COMMENTARY_POSITION = 'commentary_position', CAMERA_POSITION = 'camera_position', LIGHTING_GANTRY = 'lighting_gantry', SCOREBOARD = 'scoreboard', VIDEO_BOARD = 'video_board', SOUND_SYSTEM = 'sound_system', HVAC = 'hvac', FIRE_SUPPRESSION = 'fire_suppression', EMERGENCY_EXIT = 'emergency_exit', ACCESSIBLE_RAMP = 'accessible_ramp', ELEVATOR = 'elevator', ESCALATOR = 'escalator', PARKING = 'parking', OUTDOOR_COURT_AREA = 'outdoor_court_area', SPECTATOR_SEATING = 'spectator_seating', PLAYER_BENCH = 'player_bench', OFFICIALS_TABLE = 'officials_table', WARM_UP_AREA = 'warm_up_area', COOL_DOWN_AREA = 'cool_down_area', OTHER = 'other' }
export enum FacilityStatus { AVAILABLE = 'available', OCCUPIED = 'occupied', MAINTENANCE = 'maintenance', CLEANING = 'cleaning', RESERVED = 'reserved', OUT_OF_SERVICE = 'out_of_service', DECOMMISSIONED = 'decommissioned' }

export interface IFacilityCapacity { seated: number; standing: number; wheelchairAccessible: number; maxOccupancy: number; }
export interface IFacilityFeatures { hasHVAC: boolean; hasWiFi: boolean; hasPowerOutlets: boolean; hasWaterSupply: boolean; hasDrainage: boolean; hasNaturalLight: boolean; hasEmergencyLighting: boolean; hasFireExtinguisher: boolean; hasFirstAidKit: boolean; hasSecurityCamera: boolean; hasAccessControl: boolean; isWheelchairAccessible: boolean; hasAudioSystem: boolean; hasVideoDisplay: boolean; hasClimateControl: boolean; customFeatures: Record<string, unknown>; }
export interface IFacilityDimensions { length: number; width: number; height: number; area: number; volume: number; }

export interface IFacility extends Document {
  venueId: Types.ObjectId; facilityCode: string; name: string; facilityType: FacilityType; status: FacilityStatus; location: { floor?: string; section?: string; roomNumber?: string; coordinates?: { x: number; y: number; z: number }; nearestCourt?: Types.ObjectId; }; capacity: IFacilityCapacity; dimensions: IFacilityDimensions; features: IFacilityFeatures; assignedEquipment: Types.ObjectId[]; maintenanceSchedule: { frequency: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annually' | 'as_needed'; lastMaintenance?: Date; nextMaintenance?: Date; maintenanceTasks: string[]; }; cleaningSchedule: { frequency: 'daily' | 'weekly' | 'monthly' | 'after_each_use' | 'as_needed'; lastCleaning?: Date; nextCleaning?: Date; cleaningProtocol: string; }; utilizationMetrics: { totalBookings: number; totalHoursUsed: number; averageOccupancyRate: number; peakUsageHours: number[]; lastUpdated: Date; }; accessControl: { requiredAccessLevel: string[]; requiresKeyCard: boolean; requiresBiometric: boolean; accessHours: { start: string; end: string }[]; }; metadata: Record<string, unknown>; decommissionedAt?: Date; decommissionedReason?: string; createdAt: Date; updatedAt: Date;
}

export type FacilityDocument = HydratedDocument<IFacility>;

const FacilityCapacitySchema = new Schema<IFacilityCapacity>({ seated: { type: Number, required: true, min: 0 }, standing: { type: Number, required: true, min: 0 }, wheelchairAccessible: { type: Number, required: true, min: 0 }, maxOccupancy: { type: Number, required: true, min: 0 } }, { _id: false });
const FacilityDimensionsSchema = new Schema<IFacilityDimensions>({ length: { type: Number, required: true, min: 0 }, width: { type: Number, required: true, min: 0 }, height: { type: Number, required: true, min: 0 }, area: { type: Number, required: true, min: 0 }, volume: { type: Number, required: true, min: 0 } }, { _id: false });
const FacilityFeaturesSchema = new Schema<IFacilityFeatures>({ hasHVAC: { type: Boolean, default: false }, hasWiFi: { type: Boolean, default: false }, hasPowerOutlets: { type: Boolean, default: false }, hasWaterSupply: { type: Boolean, default: false }, hasDrainage: { type: Boolean, default: false }, hasNaturalLight: { type: Boolean, default: false }, hasEmergencyLighting: { type: Boolean, default: false }, hasFireExtinguisher: { type: Boolean, default: false }, hasFirstAidKit: { type: Boolean, default: false }, hasSecurityCamera: { type: Boolean, default: false }, hasAccessControl: { type: Boolean, default: false }, isWheelchairAccessible: { type: Boolean, default: false }, hasAudioSystem: { type: Boolean, default: false }, hasVideoDisplay: { type: Boolean, default: false }, hasClimateControl: { type: Boolean, default: false }, customFeatures: { type: Schema.Types.Mixed, default: {} } }, { _id: false });
const FacilityLocationSchema = new Schema({ floor: { type: String, trim: true }, section: { type: String, trim: true }, roomNumber: { type: String, trim: true }, coordinates: { x: { type: Number }, y: { type: Number }, z: { type: Number } }, nearestCourt: { type: Schema.Types.ObjectId, ref: 'Court' } }, { _id: false });

const FacilitySchema = new Schema<IFacility>(
  { venueId: { type: Schema.Types.ObjectId, required: true, ref: 'Venue' }, facilityCode: { type: String, required: true, trim: true, uppercase: true, maxlength: 50 }, name: { type: String, required: true, trim: true, maxlength: 200 }, facilityType: { type: String, enum: Object.values(FacilityType), required: true }, status: { type: String, enum: Object.values(FacilityStatus), default: FacilityStatus.AVAILABLE }, location: { type: FacilityLocationSchema, required: true }, capacity: { type: FacilityCapacitySchema, required: true }, dimensions: { type: FacilityDimensionsSchema, required: true }, features: { type: FacilityFeaturesSchema, required: true }, assignedEquipment: [{ type: Schema.Types.ObjectId, ref: 'Equipment' }], maintenanceSchedule: { frequency: { type: String, enum: ['daily','weekly','monthly','quarterly','annually','as_needed'], required: true }, lastMaintenance: { type: Date }, nextMaintenance: { type: Date }, maintenanceTasks: [{ type: String, trim: true }] }, cleaningSchedule: { frequency: { type: String, enum: ['daily','weekly','monthly','after_each_use','as_needed'], required: true }, lastCleaning: { type: Date }, nextCleaning: { type: Date }, cleaningProtocol: { type: String, required: true, trim: true } }, utilizationMetrics: { totalBookings: { type: Number, default: 0 }, totalHoursUsed: { type: Number, default: 0 }, averageOccupancyRate: { type: Number, default: 0, min: 0, max: 1 }, peakUsageHours: [{ type: Number, min: 0, max: 23 }], lastUpdated: { type: Date, default: Date.now } }, accessControl: { requiredAccessLevel: [{ type: String, trim: true }], requiresKeyCard: { type: Boolean, default: false }, requiresBiometric: { type: Boolean, default: false }, accessHours: [{ start: { type: String, required: true, match: /^([01]\d|2[0-3]):([0-5]\d)$/ }, end: { type: String, required: true, match: /^([01]\d|2[0-3]):([0-5]\d)$/ } }] }, metadata: { type: Schema.Types.Mixed, default: {} }, decommissionedAt: { type: Date }, decommissionedReason: { type: String, trim: true } },
  { timestamps: true, collection: 'facilities' }
);

FacilitySchema.index({ venueId: 1, facilityCode: 1 }, { unique: true });
FacilitySchema.index({ venueId: 1, facilityType: 1 });
FacilitySchema.index({ venueId: 1, status: 1 });
FacilitySchema.index({ 'location.nearestCourt': 1 });
FacilitySchema.index({ status: 1 });

FacilitySchema.virtual('isAvailable').get(function () { return this.status === FacilityStatus.AVAILABLE; });
FacilitySchema.virtual('occupancyRate').get(function () { if (this.capacity.maxOccupancy === 0) return 0; return this.utilizationMetrics.averageOccupancyRate; });

export const Facility = models.Facility || model<IFacility>('Facility', FacilitySchema);





