"""Report repositories for report, notification, and audit log operations."""

from typing import Optional, List
from uuid import UUID
from datetime import datetime

from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.repositories.base import BaseRepository
from app.models.reports import Report, Notification, AuditLog


class ReportRepository(BaseRepository):
    """Repository for Report entity."""

    def __init__(self, session):
        super().__init__(Report, session)

    async def get_by_match(self, match_id: UUID) -> List[Report]:
        """Get all reports for a match."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.match_id == match_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_by_competition(self, competition_id: UUID) -> List[Report]:
        """Get all reports for a competition."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.competition_id == competition_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_by_season(self, season_id: UUID) -> List[Report]:
        """Get all reports for a season."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.season_id == season_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_by_team(self, team_id: UUID) -> List[Report]:
        """Get all reports for a team."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.team_id == team_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_by_player(self, player_id: UUID) -> List[Report]:
        """Get all reports for a player."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.player_id == player_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_by_type(self, report_type: str) -> List[Report]:
        """Get reports by type."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.report_type == report_type)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()

    async def get_pending_reports(self) -> List[Report]:
        """Get reports pending generation."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.status.in_(["draft", "generating"]))
            .order_by(self.model.scheduled_at)
        )
        return result.scalars().all()

    async def get_generated_by(self, user_id: UUID) -> List[Report]:
        """Get reports generated by a user."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.generated_by == user_id)
            .order_by(desc(self.model.created_at))
        )
        return result.scalars().all()


class NotificationRepository(BaseRepository):
    """Repository for Notification entity."""

    def __init__(self, session):
        super().__init__(Notification, session)

    async def get_by_user(self, user_id: UUID, unread_only: bool = False) -> List[Notification]:
        """Get notifications for a user."""
        query = select(self.model).where(self.model.user_id == user_id)
        if unread_only:
            query = query.where(self.model.is_read == False)
        query = query.order_by(desc(self.model.created_at))
        result = await self.session.execute(query)
        return result.scalars().all()

    async def get_unread_count(self, user_id: UUID) -> int:
        """Get count of unread notifications for a user."""
        result = await self.session.execute(
            select(func.count(self.model.id))
            .where(self.model.user_id == user_id)
            .where(self.model.is_read == False)
        )
        return result.scalar() or 0

    async def mark_as_read(self, notification_id: UUID) -> bool:
        """Mark notification as read."""
        result = await self.session.execute(
            select(self.model).where(self.model.id == notification_id)
        )
        notification = result.scalar_one_or_none()
        if notification:
            notification.is_read = True
            notification.read_at = datetime.utcnow()
            return True
        return False

    async def mark_all_as_read(self, user_id: UUID) -> int:
        """Mark all notifications as read for a user."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.user_id == user_id)
            .where(self.model.is_read == False)
        )
        notifications = result.scalars().all()
        for n in notifications:
            n.is_read = True
            n.read_at = datetime.utcnow()
        return len(notifications)

    async def get_by_reference(self, reference_type: str, reference_id: UUID) -> List[Notification]:
        """Get notifications by reference."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.reference_type == reference_type)
            .where(self.model.reference_id == reference_id)
        )
        return result.scalars().all()

    async def create_notification(
        self,
        user_id: UUID,
        notification_type: str,
        title: str,
        message: str,
        organization_id: UUID = None,
        reference_type: str = None,
        reference_id: UUID = None,
        action_url: str = None,
        priority: int = 0
    ) -> Notification:
        """Create a new notification."""
        notification = self.model(
            user_id=user_id,
            organization_id=organization_id,
            type=notification_type,
            title=title,
            message=message,
            reference_type=reference_type,
            reference_id=reference_id,
            action_url=action_url,
            priority=priority,
        )
        self.session.add(notification)
        await self.session.flush()
        await self.session.refresh(notification)
        return notification


class AuditLogRepository(BaseRepository):
    """Repository for AuditLog entity."""

    def __init__(self, session):
        super().__init__(AuditLog, session)

    async def get_by_organization(self, org_id: UUID, limit: int = 100) -> List[AuditLog]:
        """Get audit logs for an organization."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.organization_id == org_id)
            .order_by(desc(self.model.timestamp))
            .limit(limit)
        )
        return result.scalars().all()

    async def get_by_user(self, user_id: UUID, limit: int = 100) -> List[AuditLog]:
        """Get audit logs for a user."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.user_id == user_id)
            .order_by(desc(self.model.timestamp))
            .limit(limit)
        )
        return result.scalars().all()

    async def get_by_resource(self, resource_type: str, resource_id: UUID, limit: int = 100) -> List[AuditLog]:
        """Get audit logs for a specific resource."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.resource_type == resource_type)
            .where(self.model.resource_id == resource_id)
            .order_by(desc(self.model.timestamp))
            .limit(limit)
        )
        return result.scalars().all()

    async def get_by_action(self, action: str, limit: int = 100) -> List[AuditLog]:
        """Get audit logs by action."""
        result = await self.session.execute(
            select(self.model)
            .where(self.model.action == action)
            .order_by(desc(self.model.timestamp))
            .limit(limit)
        )
        return result.scalars().all()

    async def get_by_time_range(
        self,
        start_time: datetime,
        end_time: datetime,
        org_id: UUID = None
    ) -> List[AuditLog]:
        """Get audit logs within a time range."""
        query = select(self.model).where(
            self.model.timestamp >= start_time,
            self.model.timestamp <= end_time
        )
        if org_id:
            query = query.where(self.model.organization_id == org_id)
        query = query.order_by(desc(self.model.timestamp))
        result = await self.session.execute(query)
        return result.scalars().all()

    async def log_action(
        self,
        action: str,
        resource_type: str,
        resource_id: UUID = None,
        organization_id: UUID = None,
        user_id: UUID = None,
        old_values: dict = None,
        new_values: dict = None,
        ip_address: str = None,
        user_agent: str = None,
        status: str = "success",
        error_message: str = None
    ) -> AuditLog:
        """Log an action to the audit log."""
        log = self.model(
            action=action,
            resource_type=resource_type,
            resource_id=resource_id,
            organization_id=organization_id,
            user_id=user_id,
            old_values=old_values,
            new_values=new_values,
            ip_address=ip_address,
            user_agent=user_agent,
            status=status,
            error_message=error_message,
        )
        self.session.add(log)
        await self.session.flush()
        await self.session.refresh(log)
        return log