"""Repository package for Organization module."""

from src.modules.organization.repositories.organization import (
    OrganizationRepository,
    TeamRepository,
    # PlayerRepository,  # Not yet implemented
    StaffRepository,
    StaffAssignmentRepository,
    StaffMedicalInfoRepository,
    StaffDocumentRepository,
    MedicalAssignmentRepository,
    TechnicalAssignmentRepository,
    RefereeAssignmentRepository,
    CoachAssignmentRepository,
    PlayerRegistrationRepository,
    CareerHistoryRepository,
    PlayerFaceEmbeddingRepository,
    PlayerMatchStatisticsRepository,
    TrackRecordRepository,
    PoseRecordRepository,
)

from src.modules.organization.repositories.supporting import (
    OrganizationRepository as SupportingOrganizationRepository,
    TeamRepository as SupportingTeamRepository,
    StaffRepository as SupportingStaffRepository,
    StaffAssignmentRepository as SupportingStaffAssignmentRepository,
    StaffMedicalInfoRepository,
    StaffDocumentRepository,
    MedicalAssignmentRepository,
    TechnicalAssignmentRepository,
    RefereeAssignmentRepository,
    CoachAssignmentRepository,
    PlayerRegistrationRepository,
    CareerHistoryRepository,
    PlayerFaceEmbeddingRepository,
    PlayerMatchStatisticsRepository,
    TrackRecordRepository,
    PoseRecordRepository,
    InvitationRepository,
    BrandingRepository,
    AuditRepository,
    get_repositories,
)

__all__ = [
    "OrganizationRepository",
    "TeamRepository",
    "StaffRepository",
    "StaffAssignmentRepository",
    "StaffMedicalInfoRepository",
    "StaffDocumentRepository",
    "MedicalAssignmentRepository",
    "TechnicalAssignmentRepository",
    "RefereeAssignmentRepository",
    "CoachAssignmentRepository",
    "PlayerRegistrationRepository",
    "CareerHistoryRepository",
    "PlayerFaceEmbeddingRepository",
    "PlayerMatchStatisticsRepository",
    "TrackRecordRepository",
    "PoseRecordRepository",
    "SupportingOrganizationRepository",
    "SupportingTeamRepository",
    "StaffRepository",
    "StaffAssignmentRepository",
    "StaffMedicalInfoRepository",
    "StaffDocumentRepository",
    "MedicalAssignmentRepository",
    "TechnicalAssignmentRepository",
    "RefereeAssignmentRepository",
    "CoachAssignmentRepository",
    "PlayerRegistrationRepository",
    "CareerHistoryRepository",
    "PlayerFaceEmbeddingRepository",
    "PlayerMatchStatisticsRepository",
    "TrackRecordRepository",
    "PoseRecordRepository",
    "InvitationRepository",
    "BrandingRepository",
    "AuditRepository",
    "get_repositories",
]